"""Shared runtime constants for voxmlx."""

DEFAULT_LEFT_PAD_TOKENS = 32
DEFAULT_RIGHT_PAD_TOKENS = 17
DEFAULT_DELAY_TOKENS = 6

DEFAULT_DECODER_SLIDING_WINDOW = 8192
DEFAULT_CLEAR_CACHE_INTERVAL = 2048
